### ISSUE TITLE
fatal error.

### ISSUE THREAD

**Issue by dvalansi** [clearent/wordpress#1]
Parse error: syntax error, unexpected 

Getting that issue on activation. 

Latest Stable of WP, no theme or plugin conflicts.

**Comment by carl87gt** [comment]
I am unable to reproduce this in WordPress 4.7.3 using Clearent Payments 1.7. 

What version of WordPress are you using? 4.7.3?
What version of Clearent Payments? 1.7?
Did you recently update WordPress or did your host do an automated update of WordPress? (unfortunately I have seen several plugin failures after automated updates of WordPress but haven't experienced any when initiating the update manually)

You can try to delete the plugin (verify that /wp-content/plugins/clearent-payments folder is removed) and try re-installing the plugin.

**Comment by dvalansi** [comment]
Hi, I am using current on everything, I’ve test for plugin/theme conflict and can confirm that is not the issue. 


This is the error that I am getting 


Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected '[' in /home/content/w/a/n/wandrlustadmin/html/wp-content/plugins/clearent-payments/clearent_util.php on line 127

**Comment by carl87gt** [comment]
The php error should also give you a lot more detail . . . something like . . . 

Parse error: syntax error, unexpected [variable names here], expecting [something it expected] ‘(‘ in /wp-content/plugins/[plugin name]/[php file name] on line [line number of the error]

**Comment by dvalansi** [comment]
this is all i am getting

**Comment by carl87gt** [comment]
Just saw your response with the detailed error, that is helpful.

**Comment by dvalansi** [comment]
Okay, cool. I checked to make sure there are no conflicts(theme, plugin), and I am not getting any.

**Comment by carl87gt** [comment]
Researching now. I don't anticipate any conflict issues.

**Comment by dvalansi** [comment]
Great, thank you.

**Comment by carl87gt** [comment]
The plugin uses the WordPress get_option() method to read the plugin options and that is where it is dying. It might be some corrupt data for the plugin. Have you tried deleting and re-installing the plugin?

**Comment by dvalansi** [comment]
Yes, Ive tried a few times.

**Comment by carl87gt** [comment]
Can you tell me what version of PHP you are on?

**Comment by dvalansi** [comment]
I am looking into that now. I believe I am on 5.3, i am looking to switch it to at least 5.6

**Comment by carl87gt** [comment]
The plugin will not work in version 5.3 of PHP. 

The plugin dereferences arrays that are a direct result of a function call; which is not possible in versions of PHP below 5.4.

I would recommend upgrading PHP to at least 5.6 as this is the minimal supported version of PHP. Version 5.6 no longer has active support (as of 19 Jan 2017) but it does still have security support until 31 Dec 2018.

http://php.net/supported-versions.php

**Comment by dvalansi** [comment]
I am in the process of switching php.. will let you know the results.

**Comment by carl87gt** [comment]
Excellent! I have tested the code in question on 5.3 and it produces the exact result you saw. I tested in in 5.4, 5.6, and 7.1 and it works as expected.

**Comment by dvalansi** [comment]
Sounds good. I had a feeling it was the php.. although I'm not sure why
servers with 5.3 are around. Will keep you updated.

**Comment by dvalansi** [comment]
Yes, it was the PHP, everything working now! Thanks!

**Comment by carl87gt** [comment]
Fantastic! Thanks for the update.

If you have any questions or need a sandbox key for testing, please email helpdesk@clearent.com
